---
- name: Create license directory
  file:
    path: "{{ splunk_license_dest }}"
    state: directory
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    
- name: Download license for license master
  get_url: 
    url: "{{ item }}"
    dest: "{{ splunk_license_dest }}"
    mode: 0600
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    force: "{{ splunk_update_license }}"
  with_items: "{{ splunk_licenses }}"
  when: "'license_master' in splunk_roles|default([])"
