---
- name: Download license for license master
  get_url: 
    url: "{{ splunk_license }}"
    dest: "{{ splunk_license_dest }}"
    mode: 0600
    owner: splunk
    group: splunk
    force: "{{ splunk_update_license }}"
  register: license_download
  when: "'license_master' in splunk_roles|default([])"

- name: Install license for license master
  command: "{{ splunk_home }}/bin/splunk add licenses {{ splunk_license_dest }} -auth {{ splunk_login_user }}:{{ splunk_login_pass }}"
  become_user: splunk
  when: "'license_master' in splunk_roles|default([]) and license_download.changed"
  register: license_update
  changed_when: '"restart" in license_update.stdout'
  notify: Restart Splunk

- name: Configure license slaves
  command: "{{ splunk_home }}/bin/splunk edit licenser-localslave -master_uri {{ splunk_license_master_uri }} -auth {{ splunk_login_user }}:{{ splunk_login_pass }}"
  become_user: splunk
  when: "'license_master' not in splunk_roles|default([])"
  register: license_update
  changed_when: '"restart" in license_update.stdout'
  notify: Restart Splunk