---
- name: Generate general pass4SymmKey
  command: "{{ splunk_home }}/bin/splunk hash-passwd {{ splunk_key_general }}"
  register: general_pass4SymmKey_result

- name: Generate sslPassword
  command: "{{ splunk_home }}/bin/splunk hash-passwd {{ splunk_ssl_password }}"
  register: ssl_password_result

- name: Build secret variables
  set_fact:
    hashed_general_key: "{{ general_pass4SymmKey_result.stdout }}"
    hashed_ssl_password: "{{ ssl_password_result.stdout }}"
